sudo: required

services:
  - docker

before_install:
  - docker pull obolibrary/odkfull

# command to run tests
script: cd src/ontology && sh run.sh make travis_test

#after_success:
#  coveralls


### Add your own lists here
### See https://github.com/INCATools/ontology-development-kit/issues/35
notifications:
  email:
    - obo-ci-reports-all@groups.io
